### ISSUE TITLE
translate character does not work

### ISSUE THREAD

**Issue by durandom** [mhilbrunner/foundryvtt-dnd5e-lang-de#13]
Similar as #7 and happens at the code introduced in the latest release.
This happens when I click "translate" in a character sheet. The babele translation runs, but throws an exception in dnd5e-de

I do this on a character imported from dndbeyond

```
babele.js:1352 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'book' in undefined
    at convertSource (dnd5e-de.js:547:20)
    at FieldMapping.convertSource [as converter] (dnd5e-de.js:548:22)
    at FieldMapping.translate (babele.js:1006:26)
    at FieldMapping.map (babele.js:989:28)
    at babele.js:1072:62
    at Array.reduce (<anonymous>)
    at CompendiumMapping.map (babele.js:1072:28)
    at TranslatedCompendium.translate (babele.js:1235:43)
    at Object.callback (babele.js:1337:58)
    at OnDemandTranslateDialog.submit (babele.js:1367:20)
    at OnDemandTranslateDialog._onClickButton (foundry.js:65141:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

**Comment by durandom** [comment]
rollback to the previous version lets me translate a character again
